ALTER TABLE locations ADD COLUMN IF NOT EXISTS rules_title TEXT;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS reopen_times INTEGER;

ALTER TABLE cabinets ADD COLUMN IF NOT EXISTS rules_title TEXT;
ALTER TABLE cabinets ADD COLUMN IF NOT EXISTS reopen_times INTEGER;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS reopen_count INTEGER DEFAULT 0;
